use_frameworks!

platform :ios, '9.0'

target 'QuCodeing_Example' do
  pod 'QuCodeing', :path => '../'

  target 'QuCodeing_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
